name: ile-de-france

channels:
  - defaults

dependencies:
  - matplotlib=3.1.3
  - pandas=1.0.3
  - scipy=1.4.1
  - numpy=1.18.1
  - geopandas=0.6.1
  - numba=0.49.0
  - palettable=3.3.0
  - scikit-learn=0.22.1
  - shapely=1.7.0
  - tqdm=4.46.0
  - pytables=3.6.1
  - xlrd=1.2.0
  - openpyxl=3.0.9
  - pip=20.0.2

  - pip:
    - simpledbf==0.2.6
    - synpp==1.3.1
    - python-Levenshtein==0.12.1

  # For testing
  - pytest==5.4.2
  - xlwt==1.3.0
  - pysal==1.14.4.post1
