# This is a *mamba* environment file compatible with a recent mamba-forge installation.

name: ile-de-france

channels:
  - defaults

dependencies:
  - matplotlib=3.5.0
  - pandas=1.3.4
  - scipy=1.7.2
  - numpy=1.21.4
  - geopandas=0.10.2
  - numba=0.53.0
  - palettable=3.3.0
  - scikit-learn=1.0.1
  - shapely=1.8.0
  - tqdm=4.46.0
  - pytables=3.6.1
  - xlrd=1.2.0
  - openpyxl=3.0.9
  - pip=21.3.1

  - pip:
    - simpledbf==0.2.6
    - synpp==1.3.1
    - python-Levenshtein==0.12.1

  # For testing
  - pytest==5.4.2
  - xlwt==1.3.0
  - pysal==1.14.4.post1
