name: ile-de-france

channels:
  - conda-forge

dependencies:
  - matplotlib=3.7.1
  - pandas=1.5.3
  - scipy=1.10.1
  - numpy=1.23.5
  - geopandas=0.12.2
  - numba=0.56.4
  - palettable=3.3.0
  - scikit-learn=1.2.2
  - shapely=2.0.1
  - tqdm=4.65.0
  - pytables=3.7.0
  - xlrd=2.0.1
  - openpyxl=3.1.0
  - pip=23.0.1
  - python=3.10.10
  - py7zr=0.20.8
  - pytest=7.2.2
  - xlwt=1.3.0
  - fiona=1.9.2
  - sqlite=3.42.0

  - pip:
    - synpp==1.5.1
